### ISSUE TITLE
segfault when pickling network file

### ISSUE THREAD

**Issue by perimosocordiae** [spragunr/deep_q_rl#5]
Here's the relevant part of the output from `ale_run.py`:

```
Initializing ALE RL-Glue ...
Using gpu device 0: GeForce GTX 780
/usr/local/lib/python2.7/dist-packages/theano/tensor/opt.py:2536: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  if (replace_x == replace_y and
/usr/local/lib/python2.7/dist-packages/theano/gof/cmodule.py:289: RuntimeWarning: numpy.ndarray size changed, may indicate binary incompatibility
  rval = __import__(module_name, {}, {}, [module_name])
Traceback (most recent call last):
  File "./rl_glue_ale_agent.py", line 427, in <module>
    main()
  File "./rl_glue_ale_agent.py", line 423, in main
    AgentLoader.loadAgent(NeuralAgent())
  File "/usr/local/lib/python2.7/dist-packages/rlglue/agent/AgentLoader.py", line 58, in loadAgent
    client.runAgentEventLoop()
  File "/usr/local/lib/python2.7/dist-packages/rlglue/agent/ClientAgent.py", line 144, in runAgentEventLoop
    switch[agentState](self)
  File "/usr/local/lib/python2.7/dist-packages/rlglue/agent/ClientAgent.py", line 142, in <lambda>
    Network.kAgentMessage: lambda self: self.onAgentMessage() }
  File "/usr/local/lib/python2.7/dist-packages/rlglue/agent/ClientAgent.py", line 87, in onAgentMessage
    reply = self.agent.agent_message(message)
  File "./rl_glue_ale_agent.py", line 396, in agent_message
    cPickle.dump(self.network, net_file, -1)
RuntimeError: maximum recursion depth exceeded
Segmentation fault (core dumped)
```

The `FutureWarning` isn't a big deal, and the Theano mailing list says the `RuntimeWarning` isn't an issue either.

The real problem is on the line `cPickle.dump(self.network, net_file, -1)`, when it hits the recursion limit and segfaults. It managed to produce about 15MB of output in `network_file_1.pkl` before crashing, but when I try to load the pickle it complains that the object is truncated.

**Comment by AjayTalati** [comment]
Hi, I think I had the same problem? If I remember right the default recursion limit is 1000. Perhaps you could try adding,

`import sys
sys.setrecursionlimit(10000)`

at the top of `rl_glue_ale_agent.py` Hope that works for you :)

**Comment by spragunr** [comment]
It looks like this appeared with a recent Theano release.  The code has now been updated with the fix recommended by @AjayTalati.
